// Mocks generated by Mockito 5.4.6 from annotations
// in cinebook/test/viewmodels/home_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cinebook/models/core_models.dart' as _i4;
import 'package:cinebook/services/database_service.dart' as _i2;
import 'package:cinebook/services/seed_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i2.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Movie>> getMoviesStream() => (super.noSuchMethod(
        Invocation.method(
          #getMoviesStream,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.Movie>>.empty(),
      ) as _i3.Stream<List<_i4.Movie>>);

  @override
  _i3.Stream<List<_i4.Cinema>> getCinemasStream() => (super.noSuchMethod(
        Invocation.method(
          #getCinemasStream,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.Cinema>>.empty(),
      ) as _i3.Stream<List<_i4.Cinema>>);

  @override
  _i3.Future<void> bookTicket(_i4.Ticket? ticket) => (super.noSuchMethod(
        Invocation.method(
          #bookTicket,
          [ticket],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> savePayment(_i4.Payment? payment) => (super.noSuchMethod(
        Invocation.method(
          #savePayment,
          [payment],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.UserProfile?> getUserProfile(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [uid],
        ),
        returnValue: _i3.Future<_i4.UserProfile?>.value(),
      ) as _i3.Future<_i4.UserProfile?>);

  @override
  _i3.Stream<List<_i4.Ticket>> getUserTicketsStream(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserTicketsStream,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i4.Ticket>>.empty(),
      ) as _i3.Stream<List<_i4.Ticket>>);
}

/// A class which mocks [SeedService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeedService extends _i1.Mock implements _i5.SeedService {
  MockSeedService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> seedDatabase() => (super.noSuchMethod(
        Invocation.method(
          #seedDatabase,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
